# Generated by Django 3.1.7 on 2021-03-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('1', 'M1'), ('2', 'M2'), ('3', 'M3'), ('4', 'MEOW'), ('5', 'Gen Chem'), ('6', 'EG'), ('7', 'ES'), ('8', 'PnS'), ('9', 'General')], default='9', max_length=20),
        ),
    ]
