# Generated by Django 3.1.7 on 2021-03-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questionrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionrating',
            name='rate',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1),
        ),
    ]
