# Generated by Django 3.1.7 on 2021-03-20 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0006_auto_20210320_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='question',
            name='like',
        ),
        migrations.AddField(
            model_name='answer',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to=settings.AUTH_USER_MODEL, verbose_name='disliked_by'),
        ),
        migrations.AddField(
            model_name='answer',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL, verbose_name='liked_by'),
        ),
    ]
