# Generated by Django 3.1.7 on 2021-03-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210321_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dislike',
        ),
        migrations.AddField(
            model_name='answer',
            name='dislike',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='like',
        ),
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
