# Generated by Django 3.1.7 on 2021-03-21 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0008_auto_20210322_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dislike',
        ),
        migrations.AddField(
            model_name='answer',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to=settings.AUTH_USER_MODEL, verbose_name='disliked_by'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='like',
        ),
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL, verbose_name='liked_by'),
        ),
    ]
