# Generated by Django 3.1.7 on 2021-03-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('MEOW', 'MEOW'), ('Gen Chem', 'Gen Chem'), ('EG', 'EG'), ('ES', 'ES'), ('PnS', 'PnS'), ('General', 'General')], default='General', max_length=20),
        ),
    ]
