# Generated by Django 3.1.7 on 2021-03-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
